#!/bin/bash
# end-game.sh - End the game and declare a winner
# Usage: end-game.sh <winner-id> <reason> [game-name]
#
# Updates game state and logs the game end event

set -e

WINNER="${1:?Usage: end-game.sh <winner-id> <reason> [game-name]}"
REASON="${2:?Reason required}"
GAME_NAME="${3:-markovs-chains}"

GAME_DIR="games/$GAME_NAME"
STATE_FILE="$GAME_DIR/state/game-state.json"
TURN_SIGNAL="$GAME_DIR/state/turn-signal.json"
LOG_DIR="$GAME_DIR/logs"

# Validate game state
if [ ! -f "$STATE_FILE" ]; then
  jq -n '{status: "error", error: "Game state not found"}'
  exit 1
fi

GAME_ID=$(jq -r '.gameId // "unknown"' "$STATE_FILE")
TURN_NUMBER=$(jq -r '.turnNumber // 0' "$STATE_FILE")
LIVE_LOG="$LOG_DIR/game-$GAME_ID-live.jsonl"

# Update game state
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Update state file
jq --arg status "completed" --arg winner "$WINNER" \
  '.gameStatus = $status | .winner = $winner' \
  "$STATE_FILE" > "$STATE_FILE.tmp" && mv "$STATE_FILE.tmp" "$STATE_FILE"

# Log game end event
jq -n -c \
  --arg ts "$TIMESTAMP" \
  --arg winner "$WINNER" \
  --argjson turns "$TURN_NUMBER" \
  --arg reason "$REASON" \
  '{
    timestamp: $ts,
    event: "game_end",
    winner: $winner,
    totalTurns: $turns,
    reason: $reason
  }' >> "$LIVE_LOG"

# Clean up turn signal
rm -f "$TURN_SIGNAL"

# Send notification to all players
for player_dir in "$GAME_DIR/state/messages"/player-*; do
  if [ -d "$player_dir" ]; then
    player_id=$(basename "$player_dir")
    MSG_FILE="$player_dir/game-end-$(date +%s).json"
    jq -n \
      --arg winner "$WINNER" \
      --arg reason "$REASON" \
      --arg ts "$TIMESTAMP" \
      '{
        messageId: "game-end",
        from: "gamemaster",
        to: "'"$player_id"'",
        type: "system",
        content: "Game ended",
        winner: $winner,
        reason: $reason,
        timestamp: $ts
      }' > "$MSG_FILE"
  fi
done

# Return confirmation
jq -n \
  --arg winner "$WINNER" \
  --arg reason "$REASON" \
  --argjson turns "$TURN_NUMBER" \
  --arg gid "$GAME_ID" \
  '{
    status: "game_ended",
    gameId: $gid,
    winner: $winner,
    reason: $reason,
    totalTurns: $turns,
    instruction: "Game has ended. Debug capture will be generated by stop hook."
  }'
